### PR TITLE
Add Rohm Chip Resistors

### PR DESCRIPTION
**Pull request by jue89**
I've created a pool with Rohm HV chip resistors.

### CODE REVIEW

**Comment by carrotIndustries** [comment]
level should be `community` for pools not part of the Horizon EDA project itself

**Comment by jue89** [comment]
Oh, sure. Too much copy pasta :D

**Comment by carrotIndustries** [comment]
Just one thing that I noticed the base part in your pool should have the "is base part" flag set.

**Comment by jue89** [comment]
Thank you for the review and the hint :)

**Pull request merged**
